%YAML:1.0 

sequenceSettings:
   sequenceName: rgbd_dataset_freiburg3_structure_texture_far_validation
   cameraYAML: camerasTUM/freiburg3.yaml

RGBD_TUM_dataset:
   numRGB: 796 
   numDepth: 773 
   associationsTxt: associations.txt
   
