%YAML:1.0 
sequenceSettings:
   sequenceName: table_3
   cameraYAML: camerasETH/eth.yaml

RGBD_TUM_dataset:
   numRGB: 1180
   numDepth: 1180
   associationsTxt: associated.txt
   groundtruthTxt: alignedGt1.txt