%YAML:1.0 
sequenceSettings:
   sequenceName: living_room_traj1_frei_png
   cameraYAML: camerasNUIM/nuim.yaml

RGBD_TUM_dataset:
   numRGB: 966
   numDepth: 966
   associationsTxt: associationsNew.txt
