%YAML:1.0 
 
sequenceSettings:
   sequenceName: rgbd_dataset_freiburg2_desk_secret
   cameraYAML: camerasTUM/freiburg2.yaml

RGBD_TUM_dataset:
   numRGB: 3497 
   numDepth: 3494 
   associationsTxt: rgbd_dataset_freiburg2_desk_secret/fr2_desk_val.txt   
