%YAML:1.0 

sequenceSettings:
   sequenceName: rgbd_dataset_freiburg3_long_office_household_validation
   cameraYAML: camerasTUM/freiburg3.yaml

RGBD_TUM_dataset:
   numRGB: 2676 
   numDepth: 2603 
   associationsTxt: associations.txt
