%YAML:1.0 
  
sequenceSettings:
   sequenceName: rgbd_dataset_freiburg3_structure_texture_near
   cameraYAML: camerasTUM/freiburg3.yaml

RGBD_TUM_dataset:
   numRGB: 1099 
   numDepth: 1065 
   associationsTxt: associations.txt
