%YAML:1.0 
 
sequenceSettings:
   sequenceName: rgbd_dataset_freiburg3_nostructure_texture_far
   cameraYAML: camerasTUM/freiburg3.yaml

RGBD_TUM_dataset:
   numRGB: 465 
   numDepth: 454 
   associationsTxt: associations.txt
