%YAML:1.0 

sequenceSettings:
   sequenceName: rgbd_dataset_freiburg2_xyz
   cameraYAML: camerasTUM/freiburg2.yaml

RGBD_TUM_dataset:
   numRGB: 3669 
   numDepth: 3666 
   associationsTxt: associations.txt
