%YAML:1.0 
 
sequenceSettings:
   sequenceName: rgbd_dataset_freiburg3_nostructure_texture_far_validation
   cameraYAML: camerasTUM/freiburg3.yaml

RGBD_TUM_dataset:
   numRGB: 473
   numDepth: 457
   associationsTxt: associations.txt
