%YAML:1.0 

sequenceSettings:
   sequenceName: rgbd_dataset_freiburg3_long_office_household
   cameraYAML: camerasTUM/freiburg3.yaml

RGBD_TUM_dataset:
   numRGB: 2585 
   numDepth: 2509 
   associationsTxt: associations.txt
